### ISSUE TITLE
Review of bundling draft

### ISSUE THREAD

**Issue by ghost** [OpenStarscape/starscape-protocol#8]
@wmww I've got a very rough draft of a spec for bundling in `/bundling.md`. Any comments? Seem good?

**Comment by wmww** [comment]
Two comments:
- Either remove the JSON formatting tag or remove the comments, as GitHub formatting is very angry at it.
- I think the timestamp should be a float in game seconds rather than ticks.

Using seconds prevents clients from making assumptions about the length of a game tick that will break on server changes. We might also want to expose information on both physics tick length and network tick length, but I think seconds is the most useful value. This would be seconds in the internal physics engine, which would usually be very close to real-time seconds but are not guaranteed to always match.

**Comment by ghost** [comment]
Will do both. I think you can set the language to `jsonc` to make GitHub shut up about the comments.

Having some kind of more complex mappings between physics ticks, game/server/network/whatever-we-call-them ticks, seconds, etc. could be a use for a clock object? They shouldn't be there by default anyway, so maybe the client has to do something to ask for them.

**Comment by wmww** [comment]
Yeah, a clock object would definitely make sense if we need anything fancy. I think in-game seconds is the least footgunny type of timestamp to attach to each bundle, and everything else could go on a clock object (or as properties of the root game object)
